export interface ConstOption {
  value: string;
  label: string;
}

export const IDENTIFICATION_TYPES: ConstOption[] = [
  { value: 'none', label: 'None' },
  { value: 'rsa_id', label: 'RSA ID' },
  { value: 'passport', label: 'Passport / Foreign ID' },
  { value: 'asylum_seeker', label: "Asylum Seeker's Permit" },
  { value: 'refugee', label: 'Refugee ID' },
];

export const PAYMENT_METHODS: ConstOption[] = [
  { value: 'cash', label: 'Cash' },
  { value: 'cheque', label: 'Cheque' },
  { value: 'eft_manual', label: 'EFT' },
];

export const ACCOUNT_TYPES: ConstOption[] = [
  { value: '1', label: 'Current (Cheque)' },
  { value: '2', label: 'Savings' },
  { value: '3', label: 'Transmission' },
  { value: '4', label: 'Bond' },
  { value: '6', label: 'Subscription Share' },
];

export const HOLDER_RELATIONSHIPS: ConstOption[] = [
  { value: '1', label: 'Own' },
  { value: '2', label: 'Joint' },
  { value: '3', label: 'Third Party' },
];

// Transcribed from the SimplePay "Bulk Input Export" Constants sheet (bank_account.bank_id).
export const BANKS: ConstOption[] = [
  { value: '1462381520', label: 'ABSA Bank' },
  { value: '464954524', label: 'Capitec Bank' },
  { value: '207912213', label: 'Capitec Business (formerly Mercantile Bank)' },
  { value: '1809393886', label: 'First National Bank' },
  { value: '189450181', label: 'Nedbank' },
  { value: '284678023', label: 'Standard Bank' },
  { value: '1823577098', label: '20twenty' },
  { value: '946575179', label: 'Access Bank South Africa Limited' },
  { value: '2081327577', label: 'African Bank' },
  { value: '2081327576', label: 'Albaraka' },
  { value: '560121584', label: 'Bank of Transkei' },
  { value: '1449522790', label: 'Bank of Windhoek' },
  { value: '2081327609', label: 'Bank Zero' },
  { value: '2081327518', label: 'Bidvest Bank' },
  { value: '1208050630', label: 'Boland Bank PKS' },
  { value: '1057379156', label: 'Cape of Good Hope Bank' },
  { value: '638517993', label: 'Citibank South Africa' },
  { value: '1359491711', label: 'Commercial Bank of Namibia' },
  { value: '2081327605', label: 'Discovery Bank' },
  { value: '1102524399', label: 'Fidelity Bank' },
  { value: '2081327606', label: 'Finbond Mutual Bank' },
  { value: '917512057', label: 'Future Bank Corporation' },
  { value: '2081327592', label: 'GoTyme Bank (formerly Tyme Digital Bank)' },
  { value: '2081327607', label: 'Grindrod Bank' },
  { value: '1651121208', label: 'HBZ Bank' },
  { value: '1229410299', label: 'HSBC' },
  { value: '359476398', label: 'Investec Bank' },
  { value: '2081327574', label: 'Ithala' },
  { value: '2081327618', label: 'J.P. Morgan Chase Bank' },
  { value: '2070105475', label: 'Natal Building Society' },
  { value: '1347296834', label: 'Old Mutual' },
  { value: '2081327610', label: 'Olympus Mobile' },
  { value: '2081327653', label: 'OM Bank' },
  { value: '1695012897', label: "People's Bank" },
  { value: '302049463', label: 'Permanent Bank' },
  { value: '1044414317', label: "Pick 'n Pay Go Banking" },
  { value: '2081327517', label: 'Postbank' },
  { value: '659107544', label: 'Rand Merchant Bank' },
  { value: '185186574', label: 'Saambou Bank' },
  { value: '2081327590', label: 'SASFIN Bank' },
  { value: '2081327652', label: 'Standard Chartered Bank' },
  { value: '2081327519', label: 'UBank (formerly Teba Bank)' },
  { value: '2081327516', label: 'Unibank' },
  { value: '2081327575', label: 'VBS Mutual Bank' },
];

// Trimmed to the most commonly used codes plus "any country not on this list";
// covers the full ISO-alpha-3 set SimplePay accepts.
export const PASSPORT_COUNTRY_CODES: ConstOption[] = [
  { value: 'ZAF', label: 'ZAF - South Africa' },
  { value: 'ZNC', label: 'ZNC - Any country not on this list' },
  { value: 'AFG', label: 'AFG - Afghanistan' },
  { value: 'ALB', label: 'ALB - Albania' },
  { value: 'DZA', label: 'DZA - Algeria' },
  { value: 'AGO', label: 'AGO - Angola' },
  { value: 'ARG', label: 'ARG - Argentina' },
  { value: 'AUS', label: 'AUS - Australia' },
  { value: 'AUT', label: 'AUT - Austria' },
  { value: 'BGD', label: 'BGD - Bangladesh' },
  { value: 'BEL', label: 'BEL - Belgium' },
  { value: 'BWA', label: 'BWA - Botswana' },
  { value: 'BRA', label: 'BRA - Brazil' },
  { value: 'CMR', label: 'CMR - Cameroon' },
  { value: 'CAN', label: 'CAN - Canada' },
  { value: 'CHN', label: 'CHN - China' },
  { value: 'COD', label: 'COD - Democratic Republic of the Congo' },
  { value: 'EGY', label: 'EGY - Egypt' },
  { value: 'SWZ', label: 'SWZ - Eswatini (Swaziland)' },
  { value: 'ETH', label: 'ETH - Ethiopia' },
  { value: 'FRA', label: 'FRA - France' },
  { value: 'DEU', label: 'DEU - Germany' },
  { value: 'GHA', label: 'GHA - Ghana' },
  { value: 'IND', label: 'IND - India' },
  { value: 'IDN', label: 'IDN - Indonesia' },
  { value: 'IRL', label: 'IRL - Ireland' },
  { value: 'ITA', label: 'ITA - Italy' },
  { value: 'JPN', label: 'JPN - Japan' },
  { value: 'KEN', label: 'KEN - Kenya' },
  { value: 'LSO', label: 'LSO - Lesotho' },
  { value: 'MWI', label: 'MWI - Malawi' },
  { value: 'MYS', label: 'MYS - Malaysia' },
  { value: 'MOZ', label: 'MOZ - Mozambique' },
  { value: 'NAM', label: 'NAM - Namibia' },
  { value: 'NLD', label: 'NLD - Netherlands' },
  { value: 'NZL', label: 'NZL - New Zealand' },
  { value: 'NGA', label: 'NGA - Nigeria' },
  { value: 'PAK', label: 'PAK - Pakistan' },
  { value: 'PHL', label: 'PHL - Philippines' },
  { value: 'POL', label: 'POL - Poland' },
  { value: 'PRT', label: 'PRT - Portugal' },
  { value: 'RUS', label: 'RUS - Russian Federation' },
  { value: 'SAU', label: 'SAU - Saudi Arabia' },
  { value: 'SGP', label: 'SGP - Singapore' },
  { value: 'SOM', label: 'SOM - Somalia' },
  { value: 'KOR', label: 'KOR - Republic of Korea' },
  { value: 'ESP', label: 'ESP - Spain' },
  { value: 'LKA', label: 'LKA - Sri Lanka' },
  { value: 'SDN', label: 'SDN - Sudan' },
  { value: 'SWE', label: 'SWE - Sweden' },
  { value: 'CHE', label: 'CHE - Switzerland' },
  { value: 'TZA', label: 'TZA - United Republic of Tanzania' },
  { value: 'THA', label: 'THA - Thailand' },
  { value: 'TUR', label: 'TUR - Turkey' },
  { value: 'UGA', label: 'UGA - Uganda' },
  { value: 'UKR', label: 'UKR - Ukraine' },
  { value: 'ARE', label: 'ARE - United Arab Emirates' },
  { value: 'GBR', label: 'GBR - United Kingdom of Great Britain (Citizen)' },
  { value: 'USA', label: 'USA - United States of America' },
  { value: 'VEN', label: 'VEN - Venezuela' },
  { value: 'VNM', label: 'VNM - Vietnam' },
  { value: 'ZMB', label: 'ZMB - Zambia' },
  { value: 'ZWE', label: 'ZWE - Zimbabwe' },
];
